
export const GET_ERRORS = 'GET_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';

export const GET_PROFILE = 'GET_PROFILE';

export const GET_ALL_PROFILES = 'GET_ALL_PROFILES'

export const GET_PROFILE_SHOWN = 'GET_PROFILE_SHOWN'

export const GET_FRIENDS = 'GET_FRIENDS'

export const PROFILE_LOADING = 'PROFILE_LOADING';


export const GET_POSTS_LIST = 'GET_POSTS_LIST';

export const GET_POST = 'GET_POST';

export const POST_LOADING = 'POST_LOADING';

export const DELETE_POST = 'DELETE_POST';